name: delivery_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  dio: ^5.9.0
  retrofit: ^4.7.2
  logger: ^2.6.0  # for logging purpose
  json_annotation: ^4.9.0
  intl: ^0.20.2
  fpdart: ^1.1.1
  flutter_riverpod: ^2.6.1
  go_router: ^16.2.0
  app_links: ^6.4.1
  firebase_core: ^4.3.0
  firebase_analytics: ^12.0.0
  firebase_auth: ^6.0.1
  firebase_crashlytics: ^5.0.0
  cloud_firestore: ^6.1.1
  cloudinary_public: ^0.23.1
  http: ^1.2.2
  mapbox_maps_flutter: ^2.10.0
  toastification: ^3.0.3
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  freezed_annotation: ^3.1.0
  equatable: ^2.0.5
  google_nav_bar: ^5.0.7
  stomp_dart_client: ^2.1.3
  web_socket_channel: ^3.0.3
  flutter_easyloading: ^3.0.5
  cached_network_image: ^3.4.1
  flutter_screenutil: ^5.9.3
  auto_size_text: ^3.0.0
  socket_io_client: ^3.1.2
  geolocator: ^14.0.2
  geocoding: ^3.0.0
  rxdart: ^0.28.0
  image_picker: ^1.1.2
  uuid: ^4.5.1
  timeago: ^3.7.0
  local_auth: ^2.3.0
  crypto: ^3.0.3
  
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  video_player: ^2.10.1
  chewie: ^1.13.0
  agora_rtc_engine: ^6.5.3
  permission_handler: ^11.3.1


dev_dependencies:
  retrofit_generator: ^10.0.1
  build_runner: ^2.6.0
  intl_utils: ^2.8.1 # for localization
  json_serializable: ^6.10.0
  freezed: ^3.2.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  build_test: ^3.3.2
  flutter_lints: ^5.0.0
  http_mock_adapter: ^0.6.1
  # hive_generator: ^2.0.1
flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/generated
flutter:
  uses-material-design: true
  # generate: true
  
  assets:
    # - assets/images/
    - assets/icons/
    # - assets/lottie/
